name: Birthday Notifier Test

on:
  push:
    branches:
      - main

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find today's birthdays and notify Rocket.Chat
        env:
          ROCKETCHAT_WEBHOOK: ${{ secrets.ROCKETCHAT_WEBHOOK_URL }}
        run: |
          #!/usr/bin/env bash
          set -e
          
          # Get today's date in MM-DD format (adjust timezone as needed, IST is Asia/Kolkata)
          TODAY=$(TZ=Asia/Kolkata date +%m-%d)

          # Extract matching lines (excluding header)
          MATCHES=$(awk -F',' -v today="$TODAY" 'NR>1 && $2==today {print $1}' birthdays.csv)

          if [[ -n "$MATCHES" ]]; then
            MESSAGE=":tada: Birthday(s) today: $MATCHES"
            
            # Create message.json file
            cat > message.json << EOF
          {
            "text": "$MESSAGE"
          }
          EOF
            
            curl -X POST -H "Content-Type: application/json" -d @message.json $ROCKETCHAT_WEBHOOK
          else
            echo "No birthdays today."
          fi
